language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_script:
  - npm run coveralls
  - npm run coverage
  - npm run report
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
